"""Interfaces que separan casos de uso de adapters concretos."""

from __future__ import annotations

from pathlib import Path
from typing import Any, ContextManager, Protocol

from domain.modelos import Course, StoredCredentials, Task


class CredentialRepository(Protocol):
    def has_credentials(self) -> bool: ...
    def load(self) -> StoredCredentials: ...
    def save_credentials(self, username: str, password: str) -> None: ...
    def save_token(self, token: str) -> None: ...
    def clear_token(self) -> None: ...


class CampusGateway(Protocol):
    def login(self, username: str, password: str) -> str: ...
    def site_info(self, token: str) -> dict[str, Any]: ...
    def courses(self, token: str, user_id: int) -> list[dict[str, Any]]: ...
    def assignments(self, token: str) -> list[dict[str, Any]]: ...
    def submission_status(self, token: str, assignment_id: int) -> dict[str, Any]: ...
    def submission_statuses(self, token: str, assignment_ids: list[int]) -> dict[int, dict[str, Any]]: ...


class TaskRepository(Protocol):
    path: Path

    def close(self) -> None: ...
    def transaction(self) -> ContextManager[None]: ...
    def upsert_courses(self, courses: list[Course]) -> None: ...
    def upsert_tasks(self, tasks: list[Task]) -> None: ...
    def pending_tasks(self) -> list[Task]: ...
    def all_tasks(self) -> list[Task]: ...
    def count_courses(self) -> int: ...
    def changed_pending_tasks(self, tasks: list[Task]) -> list[Task]: ...
    def mark_notified(self, tasks: list[Task]) -> None: ...
    def snooze(self, assignment_id: int, until_ts: int) -> None: ...
    def clear_academic_cache(self) -> None: ...
    def clear_all_local_cache(self) -> None: ...
    def set_state(self, key: str, value: str | int | None) -> None: ...
    def get_state(self, key: str) -> str | None: ...
    def set_setting(self, key: str, value: str | int | bool) -> None: ...
    def get_setting(self, key: str, default: str | None = None) -> str | None: ...


class DesktopNotifier(Protocol):
    def notify_changed(self, tasks: list[Task]) -> None: ...


class AutostartManager(Protocol):
    def enabled(self) -> bool: ...
    def set_enabled(self, enabled: bool) -> None: ...


class DesktopNavigator(Protocol):
    def open_url(self, url: str) -> bool: ...
    def open_campus_home(self) -> bool: ...
    def open_folder(self, path: Path) -> bool: ...
